version: '2'
services:
    jhipstersamplemicroapplication-app:
        image: jhipstersamplemicroapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipstersamplemicroapplication-mysql:3306/jhipstersamplemicroapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    jhipstersamplemicroapplication-mysql:
        extends:
            file: mysql.yml
            service: jhipstersamplemicroapplication-mysql
